AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 10
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.03


#Another Experiance

# AUGMENTATION: True
# IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
# BATCH_SIZE: 16
# INCLUDE_TOP: False
# EPOCHS: 5
# CLASSES: 2
# WEIGHTS: imagenet
# LEARNING_RATE: 0.02

# AUGMENTATION: False
# IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
# BATCH_SIZE: 16
# INCLUDE_TOP: False
# EPOCHS: 3
# CLASSES: 2
# WEIGHTS: imagenet
# LEARNING_RATE: 0.08
